[package]
name = "foobarion"
version = "0.1.0"
authors = ["Cameron Reid <csreid.cr@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "foobarion"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.18"

[dependencies]
neon = "0.1.18"
